### ISSUE TITLE
LDDTool: DocBook generation does not work from any file system location

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#170]
**Describe the bug**
Looks like lddtool must be run specifically from `/path/to/lddtool-11.2.2` in order to generate a DocBook

**Fails**
```
$ ~/Downloads/lddtool-11.2.2/bin/lddtool -plD $HOME/Downloads/Archive\ \(1\)/ccb268lddinputa.xml
...
Exception in thread "main" java.io.FileNotFoundException: ./export/DD/PDS4_PDS_DD_1E00.xml (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at gov.nasa.pds.model.plugin.WriteDOMDocBook.writeDocBook(WriteDOMDocBook.java:195)
	at gov.nasa.pds.model.plugin.ExportModels.writeLDDArtifacts(ExportModels.java:211)
	at gov.nasa.pds.model.plugin.DMDocument.main(DMDocument.java:522)
```

```
$ cd ~/Downloads/lddtool-11.2.2
$ bin/lddtool -plD $HOME/Downloads/Archive\ \(1\)/ccb268lddinputa.xml
...
...
SUCCESS
```

**Comment by rchenatjpl** [comment]
lddtool still requires the existence of export/, i.e. it fails if there is no subdirectory export/ in the directory you're running from. Do I want to open another issue? No.

**Comment by jordanpadams** [comment]
@jshughes can you test this out and see what's up?

**Comment by jordanpadams** [comment]
+1 looks good @jshughes
